// Importing necessary functions from Redux Toolkit for creating a slice
import { createSlice } from '@reduxjs/toolkit'

// Creating a slice for user data handling with initial state and reducers
const userSlice = createSlice({
    name: 'myData', // Naming the slice 'myData'
    initialState: {
        data: [],      // To store user data
        loading: false, // To handle loading state
        error: null     // To handle errors
    },
    reducers: {
        // Action to trigger user data fetching and set loading to true
        fetchUserRequest: (state) => {
            state.loading = true
        },
        // Action to handle successful fetch and store the data in state
        fetchUserSuccess: (state, action) => {
            state.data = action.payload,   // Store fetched data
            state.loading = false          // Set loading to false
        },
        // Action to handle errors during fetching and reset the state
        fetchUserError: (state, action) => {
            state.error = action.payload,  // Store error message
            state.loading = false,         // Set loading to false
            data = []                      // Reset data in case of error
        }    
    }
})

// Exporting actions generated by createSlice
export const {
    fetchUserRequest,
    fetchUserSuccess,
    fetchUserError
} = userSlice.actions

// Exporting the reducer to be used in the store
export default userSlice.reducer
